<a href="https://colab.research.google.com/github/Somrat390/Machine-Learning-/blob/main/Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [5]:
df = pd.read_csv('car_price_prediction_.csv')

In [6]:
df.head()

,Car ID,Brand,Year,Engine Size,Fuel Type,Transmission,Mileage,Condition,Price,Model
0,1,Tesla,2016,2.3,Petrol,Manual,114832,New,26613.92,Model X
1,2,BMW,2018,4.4,Electric,Manual,143190,Used,14679.61,5 Series
2,3,Audi,2013,4.5,Electric,Manual,181601,New,44402.61,A4
3,4,Tesla,2011,4.1,Diesel,Automatic,68682,New,86374.33,Model Y
4,5,Ford,2009,2.6,Diesel,Manual,223009,Like New,73577.10,Mustang


In [7]:
target = df['Price']
features = df.drop('Price',axis=1)

In [9]:
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.15, random_state=20)

X_train, X_validation_test, y_train, y_validation_test =train_test_split(X_train, y_train, test_size=15/85, random_state=20)


In [10]:
print(X_test.shape)
print(X_validation_test.shape)

(375, 9)
(375, 9)


# Linear Regression

In [11]:
def predict_linear(X, w, b):
  return w * X + b

In [16]:
import numpy as np

X = np.array([1,2,3,4,5])
y = np.array([5,7,4,6,1])

In [17]:
w = 2
b = 1

prediction = predict_linear(X,w,b)

In [18]:
prediction

array([ 3,  5,  7,  9, 11])

In [22]:
w = 1
b = 0

y_pred= predict_linear(X,w,b)

In [20]:
prediction

array([1, 2, 3, 4, 5])

In [30]:
def mae(y_test,y_pred):
    erro = np.abs(y_test-y_pred)
    print(erro)
    mae = np.sum(erro)/len(erro)
    print(mae)



In [31]:
mae(y,y_pred)

[4 5 1 2 4]
3.2


its mean that predicted value and acual value average error is 3.2

In [32]:
def mse(y_test,y_pred):
    erro = (y_test-y_pred)**2
    print(erro)
    mse = np.sum(erro)/len(erro)
    print(mse)

mse(y,y_pred)

[16 25  1  4 16]
12.4


this is give the squred average error and rmse root square the mse.

Gradient descent and linear regression use mse because of its smoothness in dervative.

# Gradient

In [40]:
w = 0
b = 0
def error_with_predict(y,y_pred):
  return y - y_pred


learning_rate = 0.1

for epoch in range(1000):

    y_pred = predict_linear(X, w, b)

    error = error_with_predict(y,y_pred)



    dw = (-2*np.sum(X*error))/len(error)
    db = (-2*np.sum(error))/len(error)

    w = w - (learning_rate*dw)
    b = b - (learning_rate*db)

    if epoch % 100 == 0:
      mse = np.mean(error ** 2)

      print("epoch:", epoch)
      print("w:", w)
      print("b:", b)
      print("MSE:", mse)

epoch: 0
w: 2.4000000000000004
b: 0.9199999999999999
MSE: 25.4
epoch: 100
w: 50642706896735.69
b: 14027217751986.547
MSE: 1.7503862480819532e+28
epoch: 200
w: 1.8015203476264405e+27
b: 4.9899224882085176e+26
MSE: 2.215023886514803e+55
epoch: 300
w: 6.408574426184982e+40
b: 1.7750723542318493e+40
MSE: 2.8029989513499573e+82
epoch: 400
w: 2.2797314629314634e+54
b: 6.314490596204497e+53
MSE: 3.5470511939404622e+109
epoch: 500
w: 8.109721753163013e+67
b: 2.2462628858196522e+67
MSE: 4.4886110879118033e+136
epoch: 600
w: 2.8848830655324517e+81
b: 7.990663499037702e+80
MSE: 5.680106769516993e+163
epoch: 700
w: 1.0262436314229776e+95
b: 2.84253030034615e+94
MSE: 7.187883352157951e+190
epoch: 800
w: 3.650671334374656e+108
b: 1.0111774209186813e+108
MSE: 9.095897168958128e+217
epoch: 900
w: 1.2986586014809367e+122
b: 3.597076085525774e+121
MSE: 1.1510390646979736e+245
